spring:
  thymeleaf:
    cache: false # Ingnorar el cache para las plantillas thymeleaf
  datasource: # Config conexion a una BD
    platform: postgresql
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/PGC_HONDURAS
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: create-drop # Comprueba si las Entities corresponden con las tablas, sino las genera en la BD
    generate-ddl: true
    show-sql: true # Muestra SQL en pantalla
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
server:
    port: 8090